Troy  1.1.1
IBM/tririga-indoor-maps pull request #5
Opened 2021-07-23 05:12 UTC by SmituSingh

Hi Troy! I'm creating a pull request for the changes.

2021-07-23 19:51 UTC, troyibm requested changes

2021-07-23 19:51 UTC, troyibm commented on docs/_pages/configuring.markdown
> +triBuilding | Esri Map ID (triEsriMapIdTX) | this is a new field. For adding, refer to the installation instructions. See the following instructions for configuring. (Ex. 403b6012276b4339af152e9c3319
replace `this` with `This`.

2021-07-23 19:51 UTC, troyibm commented on docs/_pages/configuring.markdown
> +2. Click `Sign In` on top right of the landing page.
Markdown automatically numbers the numbered list correctly so you don't have to.  That's one feature of markdown that makes it more editor-friendly.  Replace all the numbers with 1.

2021-07-23 19:51 UTC, troyibm commented on docs/_pages/installation.markdown
> +=======
The single line with a single hyphen is important for Jekyll to generate the HTML from a markdown file.  Put back the -.

2021-07-23 19:51 UTC, troyibm commented on docs/_pages/configuring.markdown
> +2. Click `Sign In` on top right of the landing page.
Fix this in all the other files too.

2021-07-26 09:19 UTC, SmituSingh commented
Have made the corrections.

2021-07-26 09:19 UTC, closed without merging